In [1]:
import torch
torch.__version__

'2.1.2+cpu'

Creating tensors

In [24]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(f"Dimension of scalar: {scalar.ndim}") # getting dimension
print(f"Content of scalar: {scalar.item()}") # getting the value from the tensor - i.e. from torch.Tensor to a Python integer
print(f"Shape of scalar: {scalar.shape}") # getting shape - should be empty as a scalar has zero dimension
print(f"Device scalar is stored on: {scalar.device}")

tensor(7)
Dimension of scalar: 0
Content of scalar: 7
Shape of scalar: torch.Size([])
Device scalar is stored on: cpu


In [22]:
# vector
vector = torch.tensor([13,13,13], dtype=torch.int32) # can specify dtype when constructing the tensor. there are 10 tensor types in Torch
print(vector)
print(f"Dimension of vector: {vector.ndim}") # getting dimension
print(f"Content of vector: {vector.numpy()}") # getting the value from the tensor - i.e. from torch.Tensor to a numpy array
print(f"Shape of vector: {vector.shape}") # getting shape
print(f"Device vector is stored on: {vector.device}")

# note: work out the dimension by counting the number of brackets

tensor([13, 13, 13], dtype=torch.int32)
Dimension of vector: 1
Content of vector: [13 13 13]
Shape of vector: torch.Size([3])
Device vector is stored on: cpu


In [26]:
# Tensor
TENSOR = torch.tensor([[1, 2, 3, 4],
                        [3, 6, 9, 5],
                        [2, 4, 5, 3]])
print(f"Dimension of tensor: {TENSOR.ndim}") # getting dimension
print(f"Content of tensor: {TENSOR.numpy()}") # getting the value from the tensor - i.e. from torch.Tensor to a numpy array
print(f"Shape of tensor: {TENSOR.shape}") # getting shape - the size go outer to inner
print(f"Datatype of tensor: {TENSOR.dtype}") # getting shape - the size go outer to inner

Dimension of tensor: 2
Content of tensor: [[1 2 3 4]
 [3 6 9 5]
 [2 4 5 3]]
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.int64


Generate random tensors

In [78]:
# A 3 channel RGB image of size 4x4 pixels

# Set the random seed
# Note: Have to reset the seed every time a new rand() is called 

RANDOM_SEED=13
torch.manual_seed(seed=RANDOM_SEED) 

random_tensor = torch.rand(size=(3, 4, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.0918, 0.4794, 0.8106, 0.0151],
          [0.0153, 0.6036, 0.2318, 0.8633],
          [0.9859, 0.1975, 0.0830, 0.4253],
          [0.9149, 0.4799, 0.5348, 0.2695]],
 
         [[0.2530, 0.3390, 0.8367, 0.1289],
          [0.9693, 0.4495, 0.4031, 0.8202],
          [0.9792, 0.3278, 0.4076, 0.7276],
          [0.4506, 0.2334, 0.0411, 0.2441]],
 
         [[0.6077, 0.8273, 0.9808, 0.2711],
          [0.4097, 0.3002, 0.7334, 0.1585],
          [0.9681, 0.0544, 0.7821, 0.4113],
          [0.7642, 0.8274, 0.9497, 0.3553]]]),
 torch.float32)

In [30]:
# Create a tensor of all zeros - e.g. to do masking
zeros = torch.zeros(size=(3, 4))
print(zeros)

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)

# Create a tensor containing the identity matrix
eye = torch.eye(n=5)
print(eye)

# Create a tensor containing a range of numbers
ranges = torch.arange(start=0, end=5, step=1) # exclusive of end
print(ranges)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])


```{note}
Ensure tensors have the same shape, dtype, device. They are often the cause of issues in Pytorch
Check with my_tensor.shape, my_tensor.dtype, my_tensor.device
```

Manipulating tensors
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [37]:
# Basic operations just use operator symbols, even though torch has built-in functions like torch.mul() or torch.add()
tensor = torch.tensor([[1, 2, 3], [1, 2, 3]])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)

# Note: Tensors don't change unless reassigned

tensor([[11, 12, 13],
        [11, 12, 13]])
tensor([[-9, -8, -7],
        [-9, -8, -7]])
tensor([[10, 20, 30],
        [10, 20, 30]])
tensor([[0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000]])


In [38]:
# element-wise operation - not the same as matrix multiplication
print(tensor + tensor)
print(tensor - tensor)
print(tensor * tensor)
print(tensor / tensor)


tensor([[2, 4, 6],
        [2, 4, 6]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 4, 9],
        [1, 4, 9]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [39]:
# Matrix multiplication
# inner dimensions must match

torch.matmul(tensor, tensor.T)

# torch.matmul(tensor, torch.transpose(tensor, 0, 1)) 


tensor([[14, 14],
        [14, 14]])

Manipulating tensors

In [49]:
# reshaping

x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [52]:
x_reshaped  = x.reshape(1,8)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [62]:
x_reshaped  = x.reshape(2,4)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [56]:
# stack

torch.stack([x_reshaped, x_reshaped], dim=0)

tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]],

        [[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])